openapi: 3.0.0
info:
  title: Amazon Lightsail API
  description: >-
    Amazon Lightsail is a virtual private server (VPS) provider and is the
    easiest way to get started with AWS for developers and small businesses.
  version: '2016-11-28'
  contact:
    name: Kin Lane
    email: kin@apievangelist.com
servers:
  - url: https://lightsail.amazonaws.com
paths: {}
